[build]
  functions = "netlify/functions"
  publish = "."
  command = "echo 'Build completed'"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration globale des fonctions
[functions]
  directory = "netlify/functions"

# Configuration spécifique pour Python
[functions."*"]
  runtime = "python3.9"
[functions]
  directory = "netlify/functions"

[functions."subtitles"]
  runtime = "python3.9"