[build]
  functions = "netlify/functions"
  publish = "."
  command = "echo 'Build completed'"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/opt/buildhome/repo"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

# Variables d'environnement à configurer dans l'interface Netlify
# YOUTUBE_API_KEY = "votre_cle_youtube_api"
# NODE_ENV = "production"

# Configuration des timeouts pour les fonctions
[functions."subtitles"]
  timeout = 30