[build]
  functions = "netlify/functions"
  publish = "."
  # Pas besoin d'installer de packages externes - utilise Node.js natif
  command = "echo 'Build terminé - fonctions optimisées'"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  # Optimisations mémoire pour Node.js
  NODE_OPTIONS = "--max-old-space-size=512 --no-warnings"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  # Pas de modules externes - tout en natif
  external_node_modules = []
  directory = "netlify/functions"

# Configuration spécifique pour la fonction subtitles optimisée
[functions."subtitles"]
  timeout = 45
  memory = 1024
  node_bundler = "esbuild"
  # Variables d'environnement spécifiques
  [functions."subtitles".environment]
    NODE_ENV = "production"
    DEBUG = "false"

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers pour les functions avec optimisations
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Cache-Control = "no-cache, no-store, must-revalidate"
    # Headers pour améliorer les performances
    Keep-Alive = "timeout=30, max=100"
    Connection = "keep-alive"

# Configuration de production optimisée
[context.production.environment]
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=512"

[context.development.environment]
  NODE_ENV = "development"
  DEBUG = "true"