[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# Variables d'environnement (à configurer dans l'interface Netlify)
# YOUTUBE_API_KEY = "votre_cle_youtube_api"
# FIREBASE_PROJECT_ID = "votre_project_id"
# FIREBASE_PRIVATE_KEY = "votre_private_key"
# FIREBASE_CLIENT_EMAIL = "votre_client_email"