[build]
  functions = "netlify/functions"
  publish = "."
  command = "echo 'Build completed'"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

# Supprime la section mise qui cause l'erreur
# [build.environment.mise]
#   enabled = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

# Configuration plus simple pour Python
[functions]
  python_version = "3.9"

[functions."subtitles"]
  timeout = 30