[build]
  functions = "netlify/functions"
  publish = "."
  command = "pip install -r netlify/functions/requirements.txt"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# Configuration spécifique pour la fonction subtitles
[functions.subtitles]
  included_files = ["netlify/functions/subtitles.js", "netlify/functions/requirements.txt"]

# Variables d'environnement (à configurer dans l'interface Netlify)
# YOUTUBE_API_KEY = "optionnel_maintenant"
# NODE_ENV = "production"