[build]
  functions = "netlify/functions"
  publish = "."
  command = "npm run build"  # ← Utilise la commande de ton package.json

[build.environment]
  NODE_VERSION = "18"
  # Supprime NPM_FLAGS ou mets-le vide

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

# Configuration des timeouts pour les fonctions
[functions."subtitles"]
  timeout = 30