[build]
  functions = "netlify/functions"
  publish = "."
  
  # IMPORTANT: Build command pour installer les dépendances Python
  command = """
    echo "Installation des dépendances Python..." &&
    pip3 install --user -r netlify/functions/requirements.txt &&
    echo "Build terminé"
  """

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"
  # Ajouter le path des packages Python utilisateur
  PYTHONPATH = "/opt/buildhome/.local/lib/python3.9/site-packages:/opt/buildhome/python3.9/lib/python3.9/site-packages"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  
  # Configuration spécifique pour les fonctions Python
  [functions.subtitles]
    included_files = [
      "netlify/functions/subtitles.js", 
      "netlify/functions/requirements.txt"
    ]
    # Timeout étendu pour l'extraction
    timeout = 60

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers pour les fonctions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"