[build]
  functions = "netlify/functions"
  publish = "."
  command = "echo 'Build completed'"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"  # Force Python 3.9

# Désactive l'installation automatique de Python si nécessaire
[build.environment.mise]
  enabled = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

# Configuration Python spécifique pour les fonctions
[functions.python_settings]
  python_version = "3.9"

[functions."subtitles"]
  timeout = 30