[build]
  functions = "netlify/functions"
  publish = "."
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# Configuration des fonctions JavaScript/Node.js
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."subtitles"]
  included_files = ["node_modules/youtube-transcript/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers pour CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"